name: Mini DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mini-devops-lab .

      - name: Run Docker container
        run: docker run --rm mini-devops-lab
